//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class variable
    {
        public double Id { get; set; }
        public Nullable<double> YearId { get; set; }
        public Nullable<double> CategoryId { get; set; }
        public string Variable1 { get; set; }
        public string Description { get; set; }
    
        public virtual category category { get; set; }
        public virtual year year { get; set; }
    }
}
