//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reports.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class year
    {
        public year()
        {
            this.variables = new HashSet<variable>();
        }
    
        public Nullable<double> Year1 { get; set; }
        public double Id { get; set; }
    
        public virtual ICollection<variable> variables { get; set; }
        public virtual year year11 { get; set; }
        public virtual year year2 { get; set; }
    }
}
